"""
Comprehensive unit tests for SecureMailScope.

Tests the full pipeline against labeled synthetic PCAPs:
- Phase 1: PCAP parsing, TCP reassembly, protocol/STARTTLS identification
- Phase 2: Rule engine (every rule fires on intended fixtures, silent on good)
- Phase 3: AI/ML risk scoring, anomaly detection, feature vectors

Test data generated by scripts/generate_test_pcaps.py with labels in labels.json.
"""

from __future__ import annotations

import json
from datetime import UTC
from pathlib import Path

import numpy as np
import pytest

# ── Fixtures directory ──

FIXTURES_DIR = Path(__file__).parent.parent / "fixtures" / "pcaps"
LABELS_PATH = FIXTURES_DIR / "labels.json"


@pytest.fixture(scope="module")
def labels() -> dict:
    """Load the test labels from labels.json."""
    with open(LABELS_PATH) as f:
        return json.load(f)


def _get_pcap_path(scenario_name: str) -> Path:
    return FIXTURES_DIR / f"{scenario_name}.pcap"


# ── Helpers: run pipeline stages on a single PCAP ──

def _analyze_pcap(pcap_path: Path):
    """Run Stages 1-3 on a PCAP and return pipeline results."""
    from securemailscope.ingest.pcap_reader import read_pcap
    from securemailscope.ingest.protocol_id import identify_protocol
    from securemailscope.ingest.tcp_stream import reassemble_stream
    from securemailscope.tls.cert_parser import parse_certificate_chain
    from securemailscope.tls.fingerprint import compute_fingerprints
    from securemailscope.tls.handshake_parser import parse_handshake

    streams = read_pcap(str(pcap_path))
    assert len(streams) >= 1, f"No streams found in {pcap_path.name}"

    # Take the first (and typically only) stream
    stream = streams[0]
    reassembled = reassemble_stream(stream)
    proto_id = identify_protocol(reassembled)

    parsed_hs = None
    parsed_certs = []
    fingerprints = None

    if proto_id.tls_mode.value != "none":
        parsed_hs = parse_handshake(
            reassembled.client_to_server.data,
            reassembled.server_to_client.data,
            proto_id.tls_offset_client,
            proto_id.tls_offset_server,
        )
        if parsed_hs.raw_certificates:
            parsed_certs = parse_certificate_chain(parsed_hs.raw_certificates)
        fingerprints = compute_fingerprints(
            parsed_hs.client_hello, parsed_hs.server_hello
        )

    return {
        "stream": stream,
        "reassembled": reassembled,
        "proto_id": proto_id,
        "handshake": parsed_hs,
        "certificates": parsed_certs,
        "fingerprints": fingerprints,
    }


def _run_rules(proto_id, parsed_hs, parsed_certs, reassembled):
    """Run rule engine and return findings."""
    import json as _json

    from securemailscope.db.models import Certificate, Session, TLSHandshake, TLSMode
    from securemailscope.rules.engine import RuleEngine

    # Build model objects (not persisted — just for rule evaluation)
    session = Session(
        id=1,
        pcap_source="test",
        src_ip=reassembled.client_ip,
        dst_ip=reassembled.server_ip,
        src_port=reassembled.client_port,
        dst_port=reassembled.server_port,
        protocol=proto_id.protocol,
        tls_mode=proto_id.tls_mode,
        starttls_advertised=proto_id.starttls_advertised,
        starttls_completed=proto_id.starttls_completed,
    )

    handshake_model = None
    cert_models = []

    if parsed_hs and proto_id.tls_mode != TLSMode.NONE:
        handshake_model = TLSHandshake(
            id=1,
            session_id=1,
            tls_version_offered=_json.dumps(parsed_hs.tls_version_offered),
            tls_version_negotiated=parsed_hs.tls_version_negotiated,
            cipher_suite_negotiated=parsed_hs.cipher_suite_negotiated,
            key_exchange_type=parsed_hs.key_exchange_type,
            forward_secrecy=parsed_hs.forward_secrecy,
            visibility_limited=parsed_hs.visibility_limited,
        )

        for pc in parsed_certs:
            cert_model = Certificate(
                id=1,
                handshake_id=1,
                chain_position=pc.chain_position,
                subject=pc.subject,
                issuer=pc.issuer,
                san=_json.dumps(pc.san),
                not_before=pc.not_before,
                not_after=pc.not_after,
                public_key_algorithm=pc.public_key_algorithm,
                key_length_bits=pc.key_length_bits,
                signature_algorithm=pc.signature_algorithm,
                self_signed=pc.self_signed,
                chain_valid=pc.chain_valid,
            )
            cert_models.append(cert_model)

    engine = RuleEngine()
    findings = engine.evaluate_session(session, handshake_model, cert_models)
    return findings, session, handshake_model, cert_models


# ════════════════════════════════════════════════════════════════════════
# Phase 1 Tests: PCAP Parsing, TCP Reassembly, Protocol ID
# ════════════════════════════════════════════════════════════════════════


class TestPcapReader:
    """Test PCAP reading and stream extraction."""

    @pytest.mark.parametrize("scenario", [
        "smtp_tls12_good", "smtp_tls13_good", "smtp_tls10_rc4",
        "smtp_expired_cert", "smtp_self_signed_weak_key",
        "smtp_starttls_stripped", "smtp_plaintext",
        "imap_tls12_good", "pop3_sha1_cert", "smtp_no_forward_secrecy",
    ])
    def test_pcap_reads_without_error(self, scenario):
        """Every test PCAP should load without error."""
        from securemailscope.ingest.pcap_reader import read_pcap
        streams = read_pcap(str(_get_pcap_path(scenario)))
        assert len(streams) >= 1

    def test_pcap_file_not_found(self):
        """Missing PCAP should raise FileNotFoundError."""
        from securemailscope.ingest.pcap_reader import read_pcap
        with pytest.raises(FileNotFoundError):
            read_pcap("/nonexistent/test.pcap")


class TestProtocolIdentification:
    """Test protocol detection matches labels.json."""

    @pytest.mark.parametrize("scenario", [
        "smtp_tls12_good", "smtp_tls13_good", "smtp_tls10_rc4",
        "smtp_expired_cert", "smtp_self_signed_weak_key",
        "smtp_starttls_stripped", "smtp_plaintext",
    ])
    def test_smtp_detection(self, scenario, labels):
        """SMTP sessions should be identified as SMTP."""
        result = _analyze_pcap(_get_pcap_path(scenario))
        assert result["proto_id"].protocol.value == "smtp", \
            f"{scenario}: expected smtp, got {result['proto_id'].protocol.value}"

    def test_imap_detection(self, labels):
        """IMAP session should be identified as IMAP."""
        result = _analyze_pcap(_get_pcap_path("imap_tls12_good"))
        assert result["proto_id"].protocol.value == "imap"

    def test_pop3_detection(self, labels):
        """POP3 session should be identified as POP3."""
        result = _analyze_pcap(_get_pcap_path("pop3_sha1_cert"))
        assert result["proto_id"].protocol.value == "pop3"


class TestTLSMode:
    """Test TLS mode detection matches labels.json."""

    @pytest.mark.parametrize("scenario,expected_mode", [
        ("smtp_tls12_good", "starttls"),
        ("smtp_tls13_good", "implicit"),
        ("smtp_tls10_rc4", "starttls"),
        ("smtp_expired_cert", "starttls"),
        ("smtp_self_signed_weak_key", "starttls"),
        ("smtp_plaintext", "none"),
        ("imap_tls12_good", "implicit"),
        ("pop3_sha1_cert", "starttls"),
        ("smtp_no_forward_secrecy", "implicit"),
    ])
    def test_tls_mode(self, scenario, expected_mode, labels):
        result = _analyze_pcap(_get_pcap_path(scenario))
        assert result["proto_id"].tls_mode.value == expected_mode, \
            f"{scenario}: expected tls_mode={expected_mode}, got {result['proto_id'].tls_mode.value}"

    def test_starttls_advertised_and_completed(self, labels):
        """STARTTLS should be marked as both advertised and completed."""
        result = _analyze_pcap(_get_pcap_path("smtp_tls12_good"))
        assert result["proto_id"].starttls_advertised is True
        assert result["proto_id"].starttls_completed is True

    def test_starttls_advertised_not_completed(self, labels):
        """Stripped STARTTLS: advertised=True, completed=False."""
        result = _analyze_pcap(_get_pcap_path("smtp_starttls_stripped"))
        assert result["proto_id"].starttls_advertised is True


class TestTLSHandshake:
    """Test TLS handshake parsing matches labels.json."""

    @pytest.mark.parametrize("scenario,expected_version", [
        ("smtp_tls12_good", "TLS1.2"),
        ("smtp_tls13_good", "TLS1.3"),
        ("smtp_tls10_rc4", "TLS1.0"),
        ("smtp_expired_cert", "TLS1.2"),
        ("smtp_self_signed_weak_key", "TLS1.2"),
        ("imap_tls12_good", "TLS1.2"),
        ("pop3_sha1_cert", "TLS1.2"),
        ("smtp_no_forward_secrecy", "TLS1.2"),
    ])
    def test_tls_version(self, scenario, expected_version, labels):
        result = _analyze_pcap(_get_pcap_path(scenario))
        hs = result["handshake"]
        assert hs is not None, f"{scenario}: no handshake parsed"
        assert hs.tls_version_negotiated == expected_version, \
            f"{scenario}: expected {expected_version}, got {hs.tls_version_negotiated}"

    @pytest.mark.parametrize("scenario,expected_cipher", [
        ("smtp_tls12_good", "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"),
        ("smtp_tls13_good", "TLS_AES_128_GCM_SHA256"),
        ("smtp_tls10_rc4", "TLS_RSA_WITH_RC4_128_SHA"),
        ("smtp_no_forward_secrecy", "TLS_RSA_WITH_AES_128_GCM_SHA256"),
    ])
    def test_cipher_suite(self, scenario, expected_cipher, labels):
        result = _analyze_pcap(_get_pcap_path(scenario))
        hs = result["handshake"]
        assert hs.cipher_suite_negotiated == expected_cipher

    @pytest.mark.parametrize("scenario,expected_fs", [
        ("smtp_tls12_good", True),
        ("smtp_tls13_good", True),
        ("smtp_tls10_rc4", False),
        ("smtp_no_forward_secrecy", False),
        ("smtp_self_signed_weak_key", False),
    ])
    def test_forward_secrecy(self, scenario, expected_fs, labels):
        result = _analyze_pcap(_get_pcap_path(scenario))
        hs = result["handshake"]
        assert hs.forward_secrecy == expected_fs

    def test_tls13_visibility_limited(self, labels):
        """TLS 1.3 sessions should have visibility_limited=True."""
        result = _analyze_pcap(_get_pcap_path("smtp_tls13_good"))
        hs = result["handshake"]
        assert hs.visibility_limited is True


class TestCertificateParsing:
    """Test certificate extraction and parsing."""

    @pytest.mark.parametrize("scenario", [
        "smtp_tls12_good", "smtp_tls10_rc4", "smtp_expired_cert",
        "smtp_self_signed_weak_key", "imap_tls12_good", "pop3_sha1_cert",
        "smtp_no_forward_secrecy",
    ])
    def test_certificate_extracted(self, scenario, labels):
        result = _analyze_pcap(_get_pcap_path(scenario))
        assert len(result["certificates"]) >= 1, f"{scenario}: no certificates extracted"

    def test_cert_key_length(self, labels):
        """Check certificate key length matches label."""
        result = _analyze_pcap(_get_pcap_path("smtp_tls12_good"))
        cert = result["certificates"][0]
        assert cert.key_length_bits == 4096

    def test_weak_cert_key(self, labels):
        """1024-bit RSA key should be detected."""
        result = _analyze_pcap(_get_pcap_path("smtp_self_signed_weak_key"))
        cert = result["certificates"][0]
        assert cert.key_length_bits == 1024

    def test_self_signed_detection(self, labels):
        """Self-signed certs should be flagged."""
        result = _analyze_pcap(_get_pcap_path("smtp_tls12_good"))
        cert = result["certificates"][0]
        assert cert.self_signed is True

    def test_expired_cert_detection(self, labels):
        """Expired cert should have not_after in the past."""
        from datetime import datetime
        result = _analyze_pcap(_get_pcap_path("smtp_expired_cert"))
        cert = result["certificates"][0]
        now = datetime.now(UTC)
        not_after = cert.not_after
        if not_after.tzinfo is None:
            not_after = not_after.replace(tzinfo=UTC)
        assert now > not_after, "Certificate should be expired"

    def test_sha1_signature_detected(self, labels):
        """SHA-1 signature algorithm should be detected."""
        result = _analyze_pcap(_get_pcap_path("pop3_sha1_cert"))
        cert = result["certificates"][0]
        assert cert.signature_algorithm == "sha1", \
            f"Expected sha1, got {cert.signature_algorithm}"


class TestFingerprints:
    """Test JA3/JA3S/JA4/JA4S fingerprint computation."""

    @pytest.mark.parametrize("scenario", [
        "smtp_tls12_good", "smtp_tls13_good", "smtp_tls10_rc4",
        "imap_tls12_good", "pop3_sha1_cert",
    ])
    def test_ja3_computed(self, scenario, labels):
        result = _analyze_pcap(_get_pcap_path(scenario))
        fp = result["fingerprints"]
        assert fp is not None
        assert len(fp.ja3) == 32, f"{scenario}: JA3 should be 32 hex chars, got {len(fp.ja3)}"

    @pytest.mark.parametrize("scenario", [
        "smtp_tls12_good", "smtp_tls13_good", "smtp_tls10_rc4",
    ])
    def test_ja3s_computed(self, scenario, labels):
        result = _analyze_pcap(_get_pcap_path(scenario))
        fp = result["fingerprints"]
        assert len(fp.ja3s) == 32

    @pytest.mark.parametrize("scenario", [
        "smtp_tls12_good", "smtp_tls13_good", "smtp_tls10_rc4",
    ])
    def test_ja4_computed(self, scenario, labels):
        result = _analyze_pcap(_get_pcap_path(scenario))
        fp = result["fingerprints"]
        assert "_" in fp.ja4, f"{scenario}: JA4 should have underscore separators"


# ════════════════════════════════════════════════════════════════════════
# Phase 2 Tests: Rule Engine
# ════════════════════════════════════════════════════════════════════════


class TestRuleEngine:
    """Test every rule fires on intended fixtures and stays silent on good ones."""

    def _get_findings_for(self, scenario: str) -> list:
        result = _analyze_pcap(_get_pcap_path(scenario))
        findings, _, _, _ = _run_rules(
            result["proto_id"], result["handshake"],
            result["certificates"], result["reassembled"],
        )
        return findings

    def _finding_rule_ids(self, findings) -> set:
        return {f.rule_id for f in findings}

    # ── Positive tests: rules that SHOULD fire ──

    def test_deprecated_tls_fires(self, labels):
        findings = self._get_findings_for("smtp_tls10_rc4")
        assert "deprecated-tls-version" in self._finding_rule_ids(findings)

    def test_weak_cipher_fires(self, labels):
        findings = self._get_findings_for("smtp_tls10_rc4")
        assert "weak-cipher" in self._finding_rule_ids(findings)

    def test_no_forward_secrecy_fires(self, labels):
        findings = self._get_findings_for("smtp_self_signed_weak_key")
        assert "no-forward-secrecy" in self._finding_rule_ids(findings)

    def test_cert_expired_fires(self, labels):
        findings = self._get_findings_for("smtp_expired_cert")
        assert "cert-expired" in self._finding_rule_ids(findings)

    def test_weak_cert_key_fires(self, labels):
        findings = self._get_findings_for("smtp_self_signed_weak_key")
        assert "weak-cert-key-rsa" in self._finding_rule_ids(findings)

    def test_weak_cert_signature_fires(self, labels):
        findings = self._get_findings_for("pop3_sha1_cert")
        assert "weak-cert-signature" in self._finding_rule_ids(findings)

    def test_self_signed_fires(self, labels):
        findings = self._get_findings_for("smtp_tls12_good")
        assert "self-signed-cert" in self._finding_rule_ids(findings)

    def test_no_tls_fires_on_plaintext(self, labels):
        findings = self._get_findings_for("smtp_plaintext")
        assert "no-tls" in self._finding_rule_ids(findings)

    def test_no_tls_fires_on_stripped(self, labels):
        findings = self._get_findings_for("smtp_starttls_stripped")
        assert "no-tls" in self._finding_rule_ids(findings)

    # ── Negative tests (false-positive checks per PRD NFR-2) ──

    def test_no_false_positives_on_good_tls12(self, labels):
        """Good TLS 1.2 should only fire self-signed-cert (test certs are self-signed)."""
        findings = self._get_findings_for("smtp_tls12_good")
        rule_ids = self._finding_rule_ids(findings)
        unexpected = rule_ids - {"self-signed-cert"}
        assert not unexpected, f"Unexpected rules fired on good TLS 1.2: {unexpected}"

    def test_no_false_positives_on_good_tls13(self, labels):
        """Good TLS 1.3 should fire zero rules (no cert visible)."""
        findings = self._get_findings_for("smtp_tls13_good")
        rule_ids = self._finding_rule_ids(findings)
        assert len(rule_ids) == 0, f"Unexpected rules fired on good TLS 1.3: {rule_ids}"

    def test_no_deprecated_tls_on_good(self, labels):
        findings = self._get_findings_for("smtp_tls12_good")
        assert "deprecated-tls-version" not in self._finding_rule_ids(findings)

    def test_no_weak_cipher_on_good(self, labels):
        findings = self._get_findings_for("smtp_tls12_good")
        assert "weak-cipher" not in self._finding_rule_ids(findings)

    def test_no_cert_expired_on_valid(self, labels):
        findings = self._get_findings_for("smtp_tls12_good")
        assert "cert-expired" not in self._finding_rule_ids(findings)

    # ── Comprehensive labels check ──

    @pytest.mark.parametrize("scenario", [
        "smtp_tls12_good", "smtp_tls13_good", "smtp_tls10_rc4",
        "smtp_expired_cert", "smtp_self_signed_weak_key",
        "smtp_starttls_stripped", "smtp_plaintext",
        "imap_tls12_good", "pop3_sha1_cert", "smtp_no_forward_secrecy",
    ])
    def test_expected_rules_fired(self, scenario, labels):
        """Every rule in expected_rules_fired must actually fire."""
        expected = set(labels[scenario].get("expected_rules_fired", []))
        findings = self._get_findings_for(scenario)
        actual = self._finding_rule_ids(findings)
        missing = expected - actual
        assert not missing, f"{scenario}: expected rules {missing} did not fire. Fired: {actual}"

    @pytest.mark.parametrize("scenario", [
        "smtp_tls12_good", "smtp_tls13_good", "smtp_tls10_rc4",
        "smtp_expired_cert", "smtp_self_signed_weak_key",
        "smtp_starttls_stripped", "smtp_plaintext",
        "imap_tls12_good", "pop3_sha1_cert", "smtp_no_forward_secrecy",
    ])
    def test_expected_rules_silent(self, scenario, labels):
        """Every rule in expected_rules_silent must NOT fire (false-positive check)."""
        silent = set(labels[scenario].get("expected_rules_silent", []))
        findings = self._get_findings_for(scenario)
        actual = self._finding_rule_ids(findings)
        false_positives = silent & actual
        assert not false_positives, f"{scenario}: false positive — rules {false_positives} fired unexpectedly"


# ════════════════════════════════════════════════════════════════════════
# Phase 3 Tests: AI/ML Risk Scoring & Anomaly Detection
# ════════════════════════════════════════════════════════════════════════


class TestFeatureVector:
    """Test feature vector building."""

    def _build_fv(self, scenario: str):

        from securemailscope.ai.features import build_feature_vector

        result = _analyze_pcap(_get_pcap_path(scenario))
        findings, session, handshake_model, cert_models = _run_rules(
            result["proto_id"], result["handshake"],
            result["certificates"], result["reassembled"],
        )
        fv = build_feature_vector(session, handshake_model, cert_models, findings)
        return fv, findings

    def test_feature_vector_shape(self):
        fv, _ = self._build_fv("smtp_tls12_good")
        assert len(fv.values) == len(fv.feature_names)

    def test_good_session_has_tls(self):
        fv, _ = self._build_fv("smtp_tls12_good")
        fv_dict = fv.to_dict()
        assert fv_dict["has_tls"] == 1.0

    def test_plaintext_session_no_tls(self):
        fv, _ = self._build_fv("smtp_plaintext")
        fv_dict = fv.to_dict()
        assert fv_dict["has_tls"] == 0.0

    def test_forward_secrecy_feature(self):
        fv_good, _ = self._build_fv("smtp_tls12_good")
        fv_bad, _ = self._build_fv("smtp_no_forward_secrecy")
        assert fv_good.to_dict()["forward_secrecy"] == 1.0
        assert fv_bad.to_dict()["forward_secrecy"] == 0.0


class TestRiskScoring:
    """Test risk scoring produces correct tiers and scores."""

    def _score_scenario(self, scenario: str):
        from securemailscope.ai.features import build_feature_vector
        from securemailscope.ai.risk_model import RiskModel

        result = _analyze_pcap(_get_pcap_path(scenario))
        findings, session, handshake_model, cert_models = _run_rules(
            result["proto_id"], result["handshake"],
            result["certificates"], result["reassembled"],
        )
        fv = build_feature_vector(session, handshake_model, cert_models, findings)
        model = RiskModel()
        risk = model.score_session(fv, findings)
        return risk, findings

    def test_good_session_low_risk(self):
        risk, _ = self._score_scenario("smtp_tls12_good")
        assert risk.score_0_100 < 25, f"Good session should be low risk, got {risk.score_0_100}"

    def test_plaintext_session_critical_risk(self):
        risk, _ = self._score_scenario("smtp_plaintext")
        assert risk.score_0_100 >= 25, f"Plaintext session should be at least medium risk, got {risk.score_0_100}"

    def test_bad_session_high_risk(self):
        risk, _ = self._score_scenario("smtp_tls10_rc4")
        assert risk.score_0_100 >= 50, f"TLS1.0+RC4 session should be high risk, got {risk.score_0_100}"

    def test_worst_session_highest_score(self):
        """The worst-configured session should score at or near the top."""
        scores = {}
        for scenario in ["smtp_tls12_good", "smtp_tls10_rc4", "smtp_plaintext",
                         "smtp_self_signed_weak_key"]:
            risk, _ = self._score_scenario(scenario)
            scores[scenario] = risk.score_0_100

        # TLS1.0+RC4 should score higher than good TLS 1.2
        assert scores["smtp_tls10_rc4"] > scores["smtp_tls12_good"]

    def test_risk_score_has_attribution(self):
        """Every risk score should have non-empty feature attribution (FR-18)."""
        risk, _ = self._score_scenario("smtp_tls10_rc4")
        assert risk.feature_attribution
        attribution = json.loads(risk.feature_attribution)
        assert "method" in attribution

    def test_risk_tier_assigned(self):
        risk, _ = self._score_scenario("smtp_tls10_rc4")
        assert risk.tier.value in ("low", "medium", "high", "critical")


class TestAnomalyDetection:
    """Test anomaly detection flags bad sessions."""

    def test_anomaly_detector_runs(self):
        """Anomaly detector should work even with small datasets."""
        from securemailscope.ai.anomaly_model import AnomalyDetector
        from securemailscope.ai.features import build_feature_vector

        # Build feature vectors for several scenarios
        vectors = []
        for scenario in ["smtp_tls12_good", "smtp_tls13_good", "imap_tls12_good",
                         "smtp_tls10_rc4", "smtp_expired_cert",
                         "smtp_self_signed_weak_key", "smtp_plaintext"]:
            result = _analyze_pcap(_get_pcap_path(scenario))
            findings, session, handshake_model, cert_models = _run_rules(
                result["proto_id"], result["handshake"],
                result["certificates"], result["reassembled"],
            )
            fv = build_feature_vector(session, handshake_model, cert_models, findings)
            vectors.append(fv)

        detector = AnomalyDetector()
        matrix = np.array([fv.values for fv in vectors])
        detector.fit_global(matrix)

        # Score each session
        for fv in vectors:
            score = detector.score_session(fv, "test")
            assert hasattr(score, "anomaly_score")
            assert hasattr(score, "is_anomalous")


class TestHostRollup:
    """Test host-level risk score aggregation."""

    def test_host_rollup_weighted(self):
        from securemailscope.ai.features import build_feature_vector
        from securemailscope.ai.risk_model import RiskModel, compute_host_rollup

        # Score multiple scenarios
        risk_scores = []
        for scenario in ["smtp_tls12_good", "smtp_tls10_rc4"]:
            result = _analyze_pcap(_get_pcap_path(scenario))
            findings, session, handshake_model, cert_models = _run_rules(
                result["proto_id"], result["handshake"],
                result["certificates"], result["reassembled"],
            )
            fv = build_feature_vector(session, handshake_model, cert_models, findings)
            model = RiskModel()
            risk = model.score_session(fv, findings)
            risk_scores.append(risk)

        rollup = compute_host_rollup(risk_scores)
        assert 0 <= rollup <= 100
        # Weighted toward worst — should be closer to the worst score
        worst = max(r.score_0_100 for r in risk_scores)
        best = min(r.score_0_100 for r in risk_scores)
        assert rollup > (worst + best) / 2 - 5  # Weighted toward worst


# ════════════════════════════════════════════════════════════════════════
# Composite Demo PCAP Test
# ════════════════════════════════════════════════════════════════════════


class TestDemoPcap:
    """Test the composite demo PCAP works end-to-end."""

    def test_demo_pcap_loads(self):
        from securemailscope.ingest.pcap_reader import read_pcap
        demo_path = FIXTURES_DIR / "demo_composite.pcap"
        streams = read_pcap(str(demo_path))
        assert len(streams) >= 5, f"Demo PCAP should have multiple streams, got {len(streams)}"

    def test_demo_pcap_has_findings(self):
        """The composite demo should produce both clean and flagged sessions."""
        from securemailscope.ingest.pcap_reader import read_pcap
        from securemailscope.ingest.protocol_id import identify_protocol
        from securemailscope.ingest.tcp_stream import reassemble_stream

        demo_path = FIXTURES_DIR / "demo_composite.pcap"
        streams = read_pcap(str(demo_path))

        protocols_found = set()
        for stream in streams:
            reassembled = reassemble_stream(stream)
            if reassembled.client_to_server.is_empty and reassembled.server_to_client.is_empty:
                continue
            proto_id = identify_protocol(reassembled)
            if proto_id.protocol.value != "unknown":
                protocols_found.add(proto_id.protocol.value)

        # Should detect at least SMTP
        assert "smtp" in protocols_found, f"Demo should contain SMTP. Found: {protocols_found}"
